baseURL = "https://andersonbargas.com/"
languageCode = "pt-br"
DefaultContentLanguage = "pt-br"
title = "Anderson Bargas"
theme = "soho"

enableInlineShortcodes = true

summarylength = 10
enableEmoji = true

disqusShortname = "andersonbargas"
googleAnalytics = "UA-159369686-1"

[params]
author = "Anderson Bargas"
description = ""
profilePicture = "/profile/anderson.jpg"
copyright = "Anderson Bargas"
themeColor = "#4b76f7"
DisableComments = false
customCss = ["css/blog.css"]

  [[params.socialIcons]]
  icon = "fa-linkedin"
  title = "Linkedin"
  url = "https://www.linkedin.com/in/anderson-bargas-700a47119/"

  [[params.socialIcons]]
  icon = "fa-github"
  title = "GitHub"
  url = "https://github.com/AndersonBargas"

  [[params.socialIcons]]
  icon = "fa-twitter"
  title = "Twitter"
  url = "https://twitter.com/AndersonBargas"

#[menu]

#  [[menu.main]]
#  name = "Posts"
#  weight = 100
#  identifier = "posts"
#  url = "/post/"

[markup]

  [markup.highlight]
  codeFences = false
  guessSyntax = false
  hl_Lines = ""
  lineNoStart = 1
  lineNos = false
  lineNumbersInTable = true
  noClasses = true # if false, you need to provide you own custom CSS
  style = "monokai"
  tabWidth = 4